class AbstractBackend: ...


class AbstractRepositry: ...


class AbstractConnectionStore: ...


class AbstractSecretStore: ...


class FileSystemBackend(AbstractBackend): ...


class SqlalchemyBackend(AbstractBackend): ...


class HashiCorpVaultBackend(AbstractBackend): ...


class FileSystemRepositry(AbstractRepositry): ...


class SqlalchemyRepositry(AbstractRepositry): ...


class HashiCorpVaultRepositry(AbstractRepositry): ...


class ConnectionStore(AbstractConnectionStore): ...


class SecretStore(AbstractSecretStore): ...
